# -perf-subscriber properties
#
daemon.collective.myInfo=perfMadMix@:9400
connection.info=perfMadMix@:9400
#
client.micro.threshold=100000
client.idle.strategy=nop
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
channel.type=ipc
#media.driver.type=dedicated
media.driver.type=shared
#