# madrigal tests
#
appName=test-madrigal
#
# ft monitor
#
mon.conf.interval=10
mem.conf.interval=0
#
# pub/sub clients
#
client.micro.threshold=50000
#
#client.idle.strategy=backoff
client.idle.strategy=nop
#
snap.timeout.from.init=3000
snap.timeout.from.latest=3000
#
ordex.size.sequence=10
ordex.rwt.use.native=true
ordex.ibg.send.del=false
#