# instance 1 override properties
#
#jmx.mbean.port=10063
#
connection.info=x0-1_0@:7410
#
# Simulator params
#
simulator.0.connection.info=s0@localhost:7410
#
ecn=ecn0
#
sim.uid=internal.sim0
sim.pwd=sim0
#
ecn.credentials=ecn0Credentials
#