# instance 0 override properties
#
#jmx.mbean.port=10062
#
connection.info=x0-0_0@:7400
#
# Simulator params
#
simulator.0.connection.info=s0@localhost:7400
#
ecn=ecn0
#
sim.uid=internal.sim0
sim.pwd=sim0
#
ecn.credentials=ecn0Credentials
#