# exchange properties
#
appName=exchange
#
#ft.group=FT.MCACHE.MISC
connection.timeout.micros=200
#
mon.conf.interval=10
mem.conf.interval=0
#
server.micro.threshold=10000
server.idle.strategy=backoff
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
idGen.prefix=S0
#
timer.auctions.open.time=30
#
timer.open.auction.interval=1
timer.open.auction.imbalance.count=10
timer.open.auction.cutoff.slot=5
timer.open.auction.close.time=60
#
timer.close.auction.interval=1
timer.close.auction.imbalance.count=20
timer.close.auction.cutoff.slot=10
timer.close.auction.close.time=12000
#