# -pong properties
#
connection.info=perfPong@:9430
#
client.micro.threshold=100000
client.idle.strategy=busyspin
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
use.ipc.loopback=true
#channel.type=ipc
channel.type=multicast
multicast.channel=aeron:udp?endpoint=224.0.1.1:40123|interface=10.10.10.0/24
#
embedded.media.driver.enabled=false
#
pin.tlt.to.cpu=3
#