#
jmx.mbean.port=10093
#
# connection.info=myAppNumInst@destHostPort
connection.info=marketmaker0-1
#
ecn=ecn1
user.id=cl0mm
user.pwd=cl0mmPwd
#
idGen.prefix=M0_
#
midFeed.fixed.delay=5
midFeed.random.range.delay=5
#