#
jmx.mbean.port=10092
#
# connection.info=myAppNumInst@destHostPort
connection.info=marketmaker0-0
#
ecn=ecn0
user.id=cl0mm
user.pwd=cl0mmPwd
#
idGen.prefix=M0_
#
midFeed.fixed.delay=5
midFeed.random.range.delay=5
#