package net.a_cappella.cembalo;

public enum LogInOutStatus {
    LOGIN_INVALID_CREDENTIALS, LOGIN_YES, LOGIN_YES_ALREADY, LOGIN_NO_ALREADY, LOGOUT_YES, LOGOUT_ALREADY, LOGOUT_NO_DIFFERENT_CONNECTION
}
