# common properties
#
appName=lh
#
connection.timeout.millis=200
#
mon.conf.interval=10
mem.conf.interval=0
#
client.micro.threshold=10000
client.idle.strategy=nop
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
native.ioc.supported=true
shortcut.mode=true
one.request.at.a.time=false
use.del.add.for.price.change=true
strict.rwt=false
action.on.failover=ALWAYS_RESUME
#
cancel.retry.type=COUNT
cancel.retry.constant=5
#
