# d properties
#
reconnect.interval.millis=200
connection.timeout.micros=5000
#
daemon.collective.myInfo=d
#
collective.cores.list=d@
#collective.cores.list=d-160@192.168.1.160,d-170@192.168.1.170
#
#upgraded.params.file=./config/config.upgraded.properties
#