# daemons properties
#
appName=daemons
#
daemon.collective.myInfo=d
upgraded.params.file=./config/config.upgraded.properties
#
# collective
#
collective.cores.list.version=0
#140:burebista,150:dromihet,160:duras,170:scorilo,190:zamolxis
collective.cores.list=d-160@192.168.1.160,d-170@192.168.1.170
#
# ft monitor
#
mon.conf.interval=0
mem.conf.interval=0
#
# pub/sub daemons
#
#daemon.port.base=15000
#daemon.default.port.G=15000
#daemon.default.port.L=15001
#
conductor.idle.strategy=busyspin
receiver.idle.strategy=busyspin
sender.idle.strategy=busyspin
threading.mode=dedicated
#threading.mode=shared-network
#threading.mode=shared
#