# core 0 properties
#
collective.myInfo=ftEng_0@localhost:9430
#
#collective.cores.list.version=1
#collective.cores.list=ftEng_2@localhost:9432,ftEng_1@localhost:9431,ftEng_0@localhost:9430
#
upgraded.params.file=./config/config-ftEng-00.upgraded.properties
#
