# common properties
#
# presto tests
#
appName=test-presto
#
server.port=7301
#
# collective
#
collective.cores.list.version=0
collective.cores.list=ftEng_0@localhost:9430,ftEng_1@localhost:9431,ftEng_2@localhost:9432
#
# ft monitor
#
mon.conf.interval=10
mem.conf.interval=0
#
# pub/sub clients
#
client.micro.threshold=50000
#
#client.idle.strategy=backoff
client.idle.strategy=nop
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
ordex.size.sequence=10
ordex.rwt.use.native=true
ordex.ibg.send.del=false
ordex.ibg.interval=1000
#
