# -burst properties
#
connection.info=perfBurst@:9430
#
client.micro.threshold=100000
client.idle.strategy=busyspin
#
#snap.timeout.from.init=2000
#snap.timeout.from.latest=2000
#
use.ipc.loopback=false
channel.type=ipc
#channel.type=multicast
multicast.channel=aeron:udp?endpoint=224.0.1.1:40123
#
# this is just for information purpose in the DATAPOINT line and needs to be in sync with daemons-aeron threading.mode
media.driver.threading.mode=dedicated
#media.driver.threading.mode=shared-network
#media.driver.threading.mode=shared
#
# TightLoopThread
pin.tlt.to.cpu=4
#
# main Thread
pin.to.cpu=3
#