# -ping-pong properties
#
connection.info=perfPingPong@:9400
#
client.micro.threshold=100000
client.idle.strategy=busyspin
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
channel.type=ipc
media.driver.type=dedicated
#