#
jmx.mbean.port=10012
#
connection.info=credentials
#
#
appName=credentials
#
ecn.credentials.subject=ecn.credentials
credentials.subject=credentials
#
mon.conf.interval=10
mem.conf.interval=0
#
client.micro.threshold=10000
client.idle.strategy=backoff
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#