#
appName=publisher
#
mon.conf.interval=10
mem.conf.interval=0
#
client.micro.threshold=10000
client.idle.strategy=backoff
#
snap.timeout.from.init=2000
snap.timeout.from.latest=2000
#
jmx.mbean.port=10110
# connection.info=myAppNumInst@destHostPort
connection.info=publisher
#